build auths based on class Metadata
build-security/OPA-AspDotNetCore-Middleware pull request #15
Opened 2021-06-20 11:31 UTC by idocohen91

2021-06-22 13:09 UTC, eyalkraft submitted a review, later dismissed
1. This middleware is an open source project we created for the benefit of all the OPA community. This was complex for me to review (next time PR description could be useful), so I think it's almost impossible for some random developer that would want to use this middleware to understand how to use the attributes and what is the expected behaviour. please add a section to the readme explaining how to use the attribute.
2. sample application should work properly + the middleware shouldn't throw exceptions on normal use case because they result on blind allow/deny depends on `AllowOnFailure`.
![image](https://user-images.githubusercontent.com/63912106/122922096-f298e580-d36b-11eb-8f2d-093d6395cd35.png)
3. tests for this new feature are very welcome, and could also help developers understand the whole cartesian product/attribute overriding motivation. this is not a must for now since this project doesn't yet have any tests but you can be the MVP that changes that :)

2021-06-23 10:29 UTC, kfirpeled requested changes

2021-06-23 10:29 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Attributes/AuthorizeAttribute.cs
> +        public IEnumerator GetEnumerator() => Resources.GetEnumerator();
`GetEnumerator` is not needed

2021-06-23 10:29 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Build.Security.AspNetCore.Middleware.csproj
> +  <IsPackable>true</IsPackable>
interesting, what IsPackable solved you?
if you don't remember try to remove it and see if it is still needed

2021-06-23 10:29 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Request/RequestProvider.cs
> +        private IEnumerable<T[]> CartesianProduct<T>(IEnumerable<T> vector1, IEnumerable<T> vector2)
looks good, refactor to IEnumerable Extension class

2021-06-23 10:29 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Request/RequestProvider.cs
> +            var permissions = dividedPermissions.First();
Something is off here. 
`dividedPermissions` can be an empty list of strings
and `First` would throw you an exception. which is not good
please check that

2021-06-23 10:29 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Request/RequestProvider.cs
> +                permissions = tmpRes.Select(tuple => string.Join('.', tuple)).ToArray();
the separator should be in the middleware configuration

2021-06-23 10:29 UTC, kfirpeled commented on Source/SampleApplication/Controllers/ChildProjectController.cs
> +    public class ChildProjectController : ProjectController
Sample application should have some more sense in the examples

Let me know if you need help with the namings

2021-07-04 13:17 UTC, kfirpeled requested changes

2021-07-04 13:17 UTC, kfirpeled commented on Source/SampleApplication/Startup.cs
> +            app.UseBuildAuthorization(new RequestProviderOptions('.'));
FYI also it is better to have a delegate for runtime configuration
better doing it now, so we won't have breaking changes in the future

or we can add another overload, and we will keep this one as well
so keeping it that way is ok

2021-07-04 13:17 UTC, kfirpeled commented on Source/SampleApplication/Controllers/ProjectController.cs
> -    public class ProjectController : Controller
💯

2021-07-04 13:17 UTC, kfirpeled commented on Tests/OPA-AspDotNetCore-Middleware.Test/Class1Test.cs
> -    public class Class1Test
💯

2021-07-04 13:17 UTC, kfirpeled commented on Source/SampleApplication/Controllers/BaseAuthController.cs
> +    [Authorize("manager")]
manager is out of context here
I'm fine with changing it to `baseauthcontroller`

2021-07-04 13:17 UTC, kfirpeled commented on Source/SampleApplication/Controllers/InheritedAuthController.cs
> +    [Route("project/inheriteAuth")]
project is out of context
I'm fine with removing `Route` and place over the `BaseAuthController` `[Route("[controller]"]`

2021-07-04 13:17 UTC, kfirpeled commented on Source/SampleApplication/Controllers/OverrideAuthController.cs
> +    [Authorize("teacher")]
teacher is out of context
I'm fine with `"overrideauthcontroller"`
and remove `Route` - see previous comment

2021-07-04 13:17 UTC, kfirpeled commented on Source/SampleApplication/Controllers/OverrideAuthController.cs
> +        [Authorize("read", "edit")]
`edit` is out of context
maybe change it to `read` and `readonly`

2021-07-04 13:17 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Utils/RequestProviderExtensions.cs
> +                public static IEnumerable<T[]> CartesianProduct<T>(this IEnumerable<T> vector1, IEnumerable<T> vector2)
fix spacing

2021-07-04 13:17 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Utils/RequestProviderExtensions.cs
> +    public static class RequestProviderExtensions
class name is `EnumerableExtensions`

2021-07-04 13:17 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Utils/RequestProviderExtensions.cs
> +            var cartesianRes = from v1 in vector1
I wonder if the result should be name `product`

2021-07-04 13:17 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Utils/RequestProviderExtensions.cs
> +                from v2 in vector2
as for v1, v2
v - is a short for vector and not an item in the vector

2021-07-04 13:17 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Request/RequestProviderOptions.cs
> +    public class RequestProviderOptions
This is `BuildAuthorizationOptions`/ `BuildSecurityOptions`
Try and think if `RequestProviderOptions` stand for itself, in the eyes of the customer

2021-07-04 13:17 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Request/RequestProvider.cs
> +        private IEnumerable<string> CartesianProductHelper(IEnumerable<string>[] dividedPermissions, char separator)
A name of method cannot be helper - it doesn't describe what it does. it is too vague

What you do here can be named as `CalculatePermissions`

2021-07-04 13:17 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Request/RequestProvider.cs
> +        private IEnumerable<string> CartesianProductHelper(IEnumerable<string>[] dividedPermissions, char separator)
which should get the whole `options` instead of `separator`

2021-07-04 13:17 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Request/RequestProvider.cs
> +        private IEnumerable<string> CartesianProductHelper(IEnumerable<string>[] dividedPermissions, char separator)
and a list of `requiredResources`

2021-07-04 13:17 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Request/RequestProvider.cs
> +        private IEnumerable<string> CartesianProductHelper(IEnumerable<string>[] dividedPermissions, char separator)
and return an array instead of IEnumerable of strings

pay attention: everytime you call `ToArray` you make a duplication
so don't do that more than it is needed, otherwise it is just wasteful

2021-07-04 13:17 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Service/IOpaEnforcer.cs
> +        Task<bool> RunAuthorizationAsync(HttpContext context, RequestProviderOptions options);
not sure why this is publicly declared

2021-07-04 13:17 UTC, kfirpeled commented on Source/Build.Security.AspNetCore.Middleware/Service/IOpaEnforcer.cs
> +        Task<bool> RunAuthorizationAsync(HttpContext context, RequestProviderOptions options);
to me IOpaEnforcer should be initialized with options
and not get it per request..
options is something that is tight/immutable per instance

2021-07-04 13:18 UTC, kfirpeled commented on Tests/OPA-AspDotNetCore-Middleware.Test/RequestProviderTest.cs
> +    public class RequestProviderTest
`EnumerableExtensionsTests`

2021-07-04 13:19 UTC, kfirpeled commented on Tests/OPA-AspDotNetCore-Middleware.Test/RequestProviderTest.cs
> +namespace OPA_AspDotNetCore_Middleware.Test
I would love to see tests for the `CalculatePermissions` as well
lets discuss it later, not sure if it for this pr

2021-07-05 10:27 UTC, kfirpeled requested changes

2021-07-05 10:27 UTC, kfirpeled commented on Tests/OPA-AspDotNetCore-Middleware.Test/OPA-AspDotNetCore-Middleware.Test.csproj
> +    <PackageReference Include="FluentAssertions" Version="5.10.3" />
move this to the build file in the test directory

2021-07-05 16:14 UTC, amirbenun commented on Source/Build.Security.AspNetCore.Middleware/Request/RequestProvider.cs
> +                var tmpRes = permissions.CartesianProduct(x);
I think we have hidden here a more generic use case of cartesian product where the product is between more than two lists.
It could be nice if we supported `CartesianProduct(params IEnumerable<T>[] lists)`.
You can add test the new implementation to get more comfortable.

2021-07-05 16:32 UTC, kfirpeled approved these changes

2021-07-06 09:02 UTC, merged