BS-2447: BuildAuthorize Attribute
build-security/OPA-AspDotNetCore-Middleware pull request #7
Opened 2021-01-11 15:42 UTC by amirbenun

2021-01-11 17:19 UTC, eyalkraft requested changes
This must be tested locally

2021-01-11 17:19 UTC, eyalkraft commented on Source/OPA.AspNetCore.Middleware/Dto/OpaQueryRequest.cs
> +namespace Opa.AspDotNetCore.Middleware.Dto
renamed?

2021-01-11 17:19 UTC, eyalkraft commented on Source/OPA.AspNetCore.Middleware/Dto/Input.cs
> +namespace Opa.AspDotNetCore.Middleware.Dto
renamed

2021-01-11 17:19 UTC, eyalkraft commented on Source/OPA.AspNetCore.Middleware/Service/OpaEnforcer.cs
> +    public class OpaEnforcer : IOpaEnforcer
consider reverting to `IAsyncAuthorizationFilter` because this is definitely our use case

2021-01-11 17:19 UTC, eyalkraft commented on Source/OPA.AspNetCore.Middleware/Service/OpaEnforcer.cs
> +            if (endpoint == null)
does this normally happen?

2021-01-11 18:05 UTC, eyalkraft requested changes

2021-01-11 18:05 UTC, eyalkraft commented on Source/OPA.AspNetCore.Middleware/BuildAuthorizationMiddleware.cs
> +                await context.Response.WriteAsync("Forbidden");
const
or even better, we are going to have return message soon, maybe use it

2021-01-11 18:05 UTC, eyalkraft commented on Source/OPA.AspNetCore.Middleware/Extensions/ServiceCollectionExtension.cs
> +            services.Configure(configureOptions);
will this work with autofac?

2021-01-12 10:59 UTC, amirbenun commented on Source/OPA.AspNetCore.Middleware/Attributes/BuildAuthorizeAttribute.cs
> +    public class BuildAuthorizeAttribute : Attribute, IBuildAuthorizationResource
`AuthorizeAttribute` already exists in dotnet. I think we want to emphasise this is attribute is authorize **with build** .
I agree the naming is not good we should come up with a better name for it.

2021-01-12 11:01 UTC, amirbenun commented on Source/OPA.AspNetCore.Middleware/Service/IOpaEnforcer.cs
> +    public interface IOpaEnforcer
As we talked there should be a class with minimum functionality that implements a dotnet middleware or IAsyncAuthzFilter.

2021-01-12 11:03 UTC, amirbenun commented on Source/OPA.AspNetCore.Middleware/Service/IOpaService.cs
> +using System.Threading.Tasks;
I guess git didn't recognize it as a rename. To be honest I didn't know `git mv` makes it explicit.

2021-01-12 11:03 UTC, amirbenun commented on Source/OPA.AspNetCore.Middleware/Service/OpaEnforcer.cs
> +    public class OpaEnforcer : IOpaEnforcer
I should read about it.

2021-01-12 11:04 UTC, amirbenun commented on Source/OPA.AspNetCore.Middleware/Service/OpaEnforcer.cs
> +            if (endpoint == null)
It usually mean the server is about to return 404.

2021-01-12 11:09 UTC, amirbenun commented on Source/OPA.AspNetCore.Middleware/Extensions/ServiceCollectionExtension.cs
> +            services.Configure(configureOptions);
Yes, already today we use some built in DI features of dotnet. The way to work with Autofac is to create autofac container as the last step of initializations, that mean after all services were registered to the `ServiceCollection` and on its turn, autofac register them as well to its own container.

2021-01-12 12:21 UTC, eyalkraft commented on Source/OPA.AspNetCore.Middleware/Attributes/BuildAuthorizeAttribute.cs
> +    public class BuildAuthorizeAttribute : Attribute, IBuildAuthorizationResource
go for option 1 then

2021-01-12 12:26 UTC, eyalkraft commented on Source/OPA.AspNetCore.Middleware/Service/OpaEnforcer.cs
> +            if (endpoint == null)
do we try to authorize non existent endpoints?
should we?

2021-01-12 13:33 UTC, eyalkraft approved these changes
please test the created package.
down the road we'll want a nice confluence page to explain how to tests during local development

2021-01-12 13:39 UTC, merged